# Generated by Django 4.2.6 on 2023-12-05 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricesapp', '0001_initial'),
        ('descriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturedescription',
            name='price',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricesapp.price'),
        ),
    ]
