# Generated by Django 4.2.6 on 2023-12-05 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0001_initial'),
        ('galleryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(upload_to='pictures/')),
                ('description_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptions.picturedescription')),
            ],
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
