# Generated by Django 4.2.6 on 2023-12-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0004_cake'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypicture',
            name='cake_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='gallerypicture',
            name='color',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='gallerypicture',
            name='flavor',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='gallerypicture',
            name='occasion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
